name: Build Spotify2MP3

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to create'
        default: '1.2.6'
        required: true
        type: string

env:
  LEVEL: ${{ inputs.version }}

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Download and setup ffmpeg
      run: |
        mkdir -p ffmpeg
        cd ffmpeg
        curl -L https://evermeet.cx/ffmpeg/ffmpeg-7.1.1.7z -o ffmpeg.7z
        tar -xvf ffmpeg.7z
        rm -rf ffmpeg.7z

    - name: Download and setup yt-dlp
      run: |
        mkdir -p yt-dlp
        cd yt-dlp
        curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp_macos -o yt-dlp
        chmod +x yt-dlp
        
    - name: Build with PyInstaller
      run: |
        pyinstaller --windowed --name "Spotify2MP3" \
          --add-data "ffmpeg/ffmpeg:ffmpeg" \
          --add-data "yt-dlp/yt-dlp:yt-dlp" \
          --add-data "config.json:." \
          --add-data "icon.icns:." \
          --add-data "icon.ico:." \
          --icon=icon.icns \
          spotify2media.py

    - name: Zip the app
      run: |
          cd dist
          ditto -c -k --keepParent Spotify2MP3.app Spotify2MP3.zip
        
    - name: Create GitHub Draft
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ env.LEVEL }}
        name: Spotify2MP3 v${{ env.LEVEL }}
        draft: true
        prerelease: false
        files: dist/Spotify2MP3.zip